
POST http://localhost:8080/api/signup HTTP/1.1
content-type: application/json

{"userData":{"firstname":"Abdelrady","lastname":"Tantawy","email":"atantawy@mum.edu"},"password":"123","confirmpassword":"123"}
###


POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{"password":"123","email":"atantawy@mum.edu"}

###
GET http://localhost:8080/api/protected HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJBYmRlbHJhZHkiLCJsYXN0bmFtZSI6IlRhbnRhd3kiLCJlbWFpbCI6ImF0YW50YXd5QG11bS5lZHUiLCJpYXQiOjE1NjA2MTY2NTcsImV4cCI6MTU2MDY1OTg1NywiYXVkIjoiaHR0cDovL3JhZHkuaW4iLCJpc3MiOiJSYWR5IGNvcnAiLCJzdWIiOiJhdGFudGF3eUBtdW0uZWR1In0.ap0Si_v7qLy56rGMWDzhUIqQnR7ngKjC9-bOozUHyQPd0Ynl8xkJ71jmkBsdyZm0cruWG1qMLNuQfsEkE4Q6Xg
